// MIT Visual Computing Seminar: every talk, past and upcoming, in date order.
//
// Each Tuesday from today on shows as TBA, 12:00-1:00 PM in the Star Room,
// until an entry here fills it in. An entry needs only a date; add what you know:
//
//   date           'YYYY-MM-DD'
//   start, end     'HH:MM' Eastern, when not 12:00-1:00
//   title          the talk title; without one the card leads with the speaker
//   speaker, affiliation
//   location       '32-D463 Star Room' unless set
//   long, short    true for a "50 minutes" or "25 minutes" tag
//   site, scholar  the speaker's website and Google Scholar, shown as icons
//   url            a Details button (slides, an event page)
//   recording      a link that turns on the Recording button
//   photo          a square image: headshots in assets/speakers/, event art in assets/events/
//   notes          a short line under the date; may hold a link
//   abstract, bio  plain text in `backticks`; a blank line starts a new paragraph
//   cancelled      true, or a reason: the week shows "No seminar"
//   skip           'reason': the week is left off the calendar
//   talks          several talks in one slot: a list of { start, end, title, speaker, ... }

const talks = [
  // Fall 2025
  {
    date: '2025-09-09',
    title: 'Kickoff Event',
    location: '32-D463 Star Room',
    url: 'https://docs.google.com/presentation/d/1jppimjbEhUpKfYxHUp5sDO6RkALYHzPo4OGUqvYmr-A/edit?usp=sharing',
    photo: 'https://www.csail.mit.edu/sites/default/files/styles/primary_image/public/2017-08/Stata%20CROPPED_0.jpg?h=a5e20daa&itok=5FsCidwu',
  },
  {
    date: '2025-09-16',
    title: 'Coadjoint Orbits Preserving Fluid Simulation',
    speaker: 'Sina Nabizadeh',
    affiliation: 'CSAIL',
    location: '32-D463 Star Room',
    long: true,
    photo: 'https://sinabiz.github.io/images/sina25.jpeg',
  },
  {
    date: '2025-09-23',
    title: 'Verified Scheduling for Optimizing High-Level Tensor Programs',
    speaker: 'Amanda Liu',
    affiliation: 'CSAIL',
    location: '32-D463 Star Room',
    short: true,
    photo: 'https://people.csail.mit.edu/lamanda/images/avatar.jpg',
  },
  {
    date: '2025-09-30',
    title: 'A Geometric View of Data Complexity: Efficient Local Intrinsic Dimension Estimation with Diffusion Models',
    speaker: 'Hamid Kamkari',
    affiliation: 'CSAIL',
    location: '32-D507',
    long: true,
    photo: 'https://hamidrezakmk.github.io/hamid.png',
  },
  {
    date: '2025-10-07',
    title: 'Scaling World Simulators for Safe Physical Intelligence',
    speaker: 'Jingkang Wang',
    affiliation: 'University of Toronto',
    location: '32-D463 Star Room',
    long: true,
    photo: 'https://scholar.googleusercontent.com/citations?view_op=medium_photo&user=c0BTYC4AAAAJ&citpid=7',
  },
  {
    date: '2025-10-14',
    title: '3D Symmetric Tensor Field Topology',
    speaker: 'Eugene Zhang',
    affiliation: 'Oregon State University',
    location: '32-D463 Star Room',
    long: true,
    photo: 'https://engineering.oregonstate.edu/sites/engineering.oregonstate.edu/files/styles/profile_image/public/2023-04/profile-eugene-zhang.jpg?itok=1QhU6k52',
  },
  {
    date: '2025-10-21',
    title: 'PhysiOpt: Physics-Driven Shape Optimization for 3D Generative Models',
    speaker: 'Sean Zhan and Clement Jambon',
    affiliation: 'CSAIL',
    location: '32-D507',
    short: true,
    photo: 'https://adg.csail.mit.edu/wp-content/uploads/2023/09/sean_lower_res-1024x1024.jpg',
  },
  {
    date: '2025-10-28',
    title: 'Geometric Methods for Physics Simulation',
    speaker: 'Oliver Gross',
    affiliation: 'UCSD',
    location: '32-D463 Star Room',
    long: true,
    photo: 'https://olligross.github.io/images/profile-mine.jpg',
  },
  {
    date: '2025-11-04',
    speaker: 'Abe Davis',
    affiliation: 'Cornell University',
    location: '32-141',
    long: true,
    photo: 'https://www.cs.cornell.edu/abe/group/content/groupbios/abe/abe.jpeg',
  },
  { date: '2025-11-11', skip: 'Veterans Day' },
  {
    date: '2025-11-18',
    title: 'Support Function Parameterization of Convex Hulls for Fast Distance Queries',
    speaker: 'Anh Truong',
    affiliation: 'CSAIL',
    location: '32-D463 Star Room',
    long: true,
    photo: 'https://adg.csail.mit.edu/wp-content/uploads/2024/10/anh.jpg',
  },
  { date: '2025-11-25', skip: 'Thanksgiving' },
  {
    date: '2025-12-02',
    title: 'One String to Pull Them All: Fast Assembly of Curved Structures from Flat Auxetic Linkages',
    speaker: 'Akib Zaman',
    affiliation: 'CSAIL',
    location: '32-D463 Star Room',
    long: true,
    photo: 'https://adg.csail.mit.edu/wp-content/uploads/2023/09/akib-scaled-e1694743990993-768x768.jpg',
  },
  {
    date: '2025-12-09',
    title: 'Addressing the Unexpected - Anomaly Detection and AI Safety',
    speaker: 'Niv Cohen',
    affiliation: 'NYU',
    location: '32-141',
    long: true,
    photo: 'https://scholar.googleusercontent.com/citations?view_op=medium_photo&user=ZMdC3OQAAAAJ&citpid=5',
  },
  { date: '2025-12-16', skip: 'Holiday' },
  { date: '2025-12-23', skip: 'Holiday' },
  { date: '2025-12-30', skip: 'Holiday' },

  // Spring 2026
  { date: '2026-01-06', skip: 'IAP' },
  { date: '2026-01-13', skip: 'IAP' },
  { date: '2026-01-20', skip: 'IAP' },
  { date: '2026-01-27', skip: 'IAP' },
  { date: '2026-02-03', skip: 'IAP' },
  {
    date: '2026-02-17',
    title: 'Learning a distance measure from the information-estimation geometry of data',
    speaker: 'Guy Ohayon',
    affiliation: 'Flatiron Institute',
    location: '32-D463 Star Room',
    long: true,
    photo: 'https://scholar.googleusercontent.com/citations?view_op=medium_photo&user=Gso71ogAAAAJ&citpid=9',
  },
  {
    date: '2026-03-03',
    title: 'Continual learning: the Where, What, and When of Introspective Updates',
    speaker: 'Saurav Jha',
    affiliation: 'MILA',
    location: '32-D463 Star Room',
    long: true,
    photo: 'https://sauravjha.com.np/compressed_images/saurav_compressed.jpg',
  },
  {
    date: '2026-03-17',
    title: 'Wizard of Oz: An Experiential Time Machine powered by Google AI now Playing at the Las Vegas Sphere',
    speaker: 'Irfan Essa',
    affiliation: 'GeorgiaTech',
    location: '32-D463 Star Room',
    long: true,
    photo: 'https://scholar.googleusercontent.com/citations?view_op=medium_photo&user=XM97iScAAAAJ&citpid=2',
  },
  { date: '2026-03-24', skip: 'Spring Break' },
  {
    date: '2026-03-31',
    title: 'Towards self-driving MRI for fetal brain imaging',
    speaker: 'Ramya Muthukrishnan',
    affiliation: 'CSAIL',
    location: '32-D463 Star Room',
    long: true,
  },
  {
    date: '2026-04-07',
    title: 'Generative Re-Photography with Video Models',
    speaker: 'Sai Tedla',
    affiliation: 'York University',
    location: '32-D463 Star Room',
    long: true,
    photo: 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=Uim89fkAAAAJ&citpid=8',
  },
  {
    date: '2026-04-14',
    title: 'From Measurements to Structure: Annotation-Free Acquisition of Symbolic Geometry',
    speaker: 'Aditya Ganeshan',
    affiliation: 'Brown University',
    location: '32-D463 Star Room',
    long: true,
    photo: 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=Aw1Sb4gAAAAJ&citpid=3',
  },
  {
    date: '2026-04-21',
    speaker: 'Raphi Kang',
    affiliation: 'Caltech',
    location: '32-D463 Star Room',
    long: true,
    photo: 'https://scholar.googleusercontent.com/citations?view_op=medium_photo&user=49_WjdIAAAAJ&citpid=2',
  },
  {
    date: '2026-04-28',
    title: 'Geometry and Mechanics of Fluid Surfaces',
    speaker: 'Cuncheng Zhu',
    affiliation: 'UCSD',
    location: '32-370',
    long: true,
    photo: 'https://cunchengzhu.github.io/assets/images/profile.jpg',
  },

  // Fall 2026
  {
    date: '2026-09-22',
    title: 'Kickoff Event',
    location: '32-D463 Star Room',
    photo: 'https://www.csail.mit.edu/sites/default/files/styles/primary_image/public/2017-08/Stata%20CROPPED_0.jpg?h=a5e20daa&itok=5FsCidwu',
    notes: 'Intro event to kick off the year + <a href="https://docs.google.com/forms/d/e/1FAIpQLSfr710FspalOMh3pBwWqPP16boyeXcIE9K4Bqr-U-qKAVofRA/viewform" target="_blank" rel="noopener">presentation slot sign-ups</a>.',
  },
  { date: '2026-09-29', cancelled: true },
  {
    date: '2026-10-06',
    start: '12:15',
    title: 'Learning from Sensors, Learning for Sensors',
    speaker: 'Tzofi Klinghoffer',
    affiliation: 'Camera Culture Group, MIT',
    location: '32-G449 Kiva Room',
    site: 'https://www.tzofi.com',
    scholar: 'https://scholar.google.com/citations?user=U-h-AxUAAAAJ',
    photo: 'assets/speakers/tzofi-klinghoffer.webp',
    abstract: `AI systems can only reason from the information their sensors provide. Yet sensing and learning are often designed separately: sensors produce fixed, often processed measurements, and algorithms are trained afterward to interpret them. My research asks what becomes possible when we move the boundary of the learning problem earlier and treat the sensing process itself as part of visual intelligence. I will present work on learning from sensors, including recovering hidden 3D structure from indirect time-of-flight measurements and performing perception directly from sparse single-photon measurements in extreme low light, as well as learning for sensors, where downstream tasks help determine how sensing systems should be designed. Across these projects, the goal is to extract more useful information from physical sensor measurements and ultimately improve how those measurements are acquired in the first place.`,
    bio: `Tzofi Klinghoffer is a final-year Ph.D. student in the Media Lab at Massachusetts Institute of Technology. His research lies at the intersection of sensing, 3D vision/rendering, and machine learning. His goal is to enable new vision capabilities by leveraging emerging sensors with machine learning. His work has been published at vision, graphics, and imaging venues, such as CVPR, ICCV, ECCV, ICCP, and SIGGRAPH Asia, and was recognized with a Best Paper Award Finalist nomination at CVPR 2024. He is a Draper Scholar, Qualcomm Innovation Fellow, and DoD NDSEG Fellow. Prior to his PhD, Tzofi was a research scientist and machine learning engineer at MIT Lincoln Laboratory and Amazon.`,
  },
  {
    date: '2026-10-13',
    speaker: 'Laura Dodds',
    affiliation: 'Signal Kinetics Group, MIT',
    location: '32-D463 Star Room',
    site: 'https://laura-dodds.github.io',
    scholar: 'https://scholar.google.com/citations?user=KIgj3WQAAAAJ',
    photo: 'assets/speakers/laura-dodds.webp',
  },
  {
    date: '2026-10-20',
    speaker: 'Sebo Diaz',
    affiliation: 'Medical Vision Group, MIT',
    location: '32-D463 Star Room',
    site: 'https://sebo.sh',
    scholar: 'https://scholar.google.com/citations?user=NIU3SBUAAAAJ',
    photo: 'assets/speakers/sebo-diaz.webp',
  },
  {
    date: '2026-10-27',
    speaker: 'Victor Butoi',
    affiliation: 'Clinical and Applied Machine Learning Group, MIT',
    location: '32-D507',
    site: 'https://victorbutoi.github.io',
    scholar: 'https://scholar.google.com/citations?user=uJ_5zuYAAAAJ',
    photo: 'assets/speakers/victor-butoi.webp',
  },
  {
    date: '2026-11-03',
    title: 'Toward Recursive Self-Improvement in Medicine and Beyond',
    speaker: 'David Dai',
    affiliation: 'Multisensory Intelligence Group, MIT',
    location: '32-D463 Star Room',
    site: 'https://dd.works',
    scholar: 'https://scholar.google.com/citations?user=N1x7v90AAAAJ',
    photo: 'assets/speakers/david-dai.webp',
    abstract: `Medical foundation models fail on difficult cases where training data is rare. Even frontier models diagnose rare diseases poorly. Self-play could supply unlimited training tasks, but existing methods depend on a programmatic verifier that healthcare domain lacks. In this presentation, we present a two-stage approach in which a single base model recursively improves itself. First, the same model proposes diagnostic tasks grounded in a retrieved medical knowledge base, solves them, and judges its own answers, while a difficulty controller keeps tasks at the edge of the solver’s ability. Second, self-evolution extends to the reward specification, with the loop co-generating each open-ended task together with its grading rubric and hardening the rubric through an adversarial hack-then-patch cycle. Results show that accuracy scales nearly linearly with self-evolution compute while static task pools stall, that self-generated data outperforms distillation from stronger teachers, and that the resulting model surpasses frontier systems on rare-disease diagnosis at a small fraction of their cost.`,
  },
  {
    date: '2026-11-10',
    speaker: 'Jason Adhinarta',
    affiliation: 'Medical Vision Group, MIT',
    location: '32-D463 Star Room',
    site: 'https://jasonkena.github.io',
    scholar: 'https://scholar.google.com/citations?user=I2a9AJEAAAAJ',
    photo: 'assets/speakers/jason-adhinarta.webp',
  },
  {
    date: '2026-11-17',
    speaker: 'Ana Dodik',
    affiliation: 'Geometric Data Processing Group, MIT',
    location: '32-D463 Star Room',
    site: 'https://anadodik.github.io',
    scholar: 'https://scholar.google.com/citations?user=cDmCKFcAAAAJ',
    photo: 'assets/speakers/ana-dodik.webp',
  },
  { date: '2026-11-24', cancelled: 'Thanksgiving week' },
  {
    date: '2026-12-01',
    speaker: 'Antoine Salaün',
    affiliation: 'Beery Lab, MIT',
    location: '32-D463 Star Room',
    site: 'https://www.antoinesalaun.com',
    photo: 'assets/speakers/antoine-salaun.webp',
  },
  {
    date: '2026-12-08',
    speaker: 'Siddharth Somasundaram',
    affiliation: 'Camera Culture Group, MIT',
    location: '32-D463 Star Room',
    site: 'https://sidsoma.com',
    scholar: 'https://scholar.google.com/citations?user=WnLfhFQAAAAJ',
    photo: 'assets/speakers/siddharth-somasundaram.webp',
  },
];
